# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster
# --------------------------
LABEL maintainer="mahan.mirdar1381@gmail.com"
ENV PYTHONUNBUFFERED=1
# -------------------------------------------
# Set the working directory in the container
WORKDIR /usr/src/app
# Copy the requirements file into the container at /app
COPY ./requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt
COPY ./core .